# Volume 3: Pandas 1
    <Name>
    <Class>
    <Date>

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

%matplotlib inline

## Problem 1
Read in the file `crime_data.csv` into a pandas object. The file contains data on types of crimes in the U.S. from 1960 to 2016. Set the index as the column 'Year'. Skip any lines that do not contain data.

In [7]:
df = pd.read_csv("crime_data.csv", index_col=0)
df

,Population,Total,Violent,Property,Murder,Forcible Rape,Robbery,Aggravated Assault,Burglary,Larceny,Vehicle Theft
Year,,,,,,,,,,,
1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
1963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
1964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800
1965,193526000,4739400,387390,4352000,9960,23410,138690,215330,1282500,2572600,496900
1966,195576000,5223500,430180,4793300,11040,25820,157990,235330,1410100,2822000,561200
1967,197457000,5903400,499930,5403500,12240,27620,202910,257160,1632100,3111600,659800
1968,199399000,6720200,595010,6125200,13800,31670,262840,286700,1858900,3482700,783600
1969,201385000,7410900,661870,6749000,14760,37170,298850,311090,1981900,3888600,878500
1970,203235298,8098000,738820,7359200,16000,37990,349860,334970,2205000,4225800,928400
1971,206212000,8588200,816500,7771700,17780,42260,387700,368760,2399300,4424200,948200
1972,208230000,8248800,834900,7413900,18670,46850,376290,393090,2375500,4151200,887200
1973,209851000,8718100,875910,7842200,19640,51400,384220,420650,2565500,4347900,928800
1974,211392000,10253400,974720,9278700,20710,55400,442400,456210,3039200,5262500,977100
1975,213124000,11292400,1039710,10252700,20510,56090,470500,492620,3265300,5977700,1009600
1976,214659000,11349700,1004210,10345500,18780,57080,427810,500530,3108700,6270800,966000
1977,216332000,10984500,1029580,9955000,19120,63500,412610,534350,3071500,5905700,977700
1978,218059000,11209000,1085550,10123400,19560,67610,426930,571460,3128300,5991000,1004100
1979,220099000,12249500,1208030,11041500,21460,76390,480700,629480,3327700,6601000,1112800
1980,225349264,13408300,1344520,12063700,23040,82990,565840,672650,3795200,7136900,1131700
1981,229146000,13423800,1361820,12061900,22520,82500,592910,663900,3779700,7194400,1087800
1982,231534000,12974400,1322390,11652000,21010,78770,553130,669480,3447100,7142500,1062400
1983,233981000,12108600,1258090,10850500,19310,78920,506570,653290,3129900,6712800,1007900
1984,236158000,11881800,1273280,10608500,18690,84230,485010,685350,2984400,6591900,1032200
1985,238740000,12431400,1328800,11102600,18980,88670,497870,723250,3073300,6926400,1102900
1986,240132887,13211869,1489169,11722700,20613,91459,542775,834322,3241410,7257153,1224137
1987,242282918,13508700,1483999,12024700,20096,91110,517704,855088,3236184,7499900,1288674
1988,245807000,13923100,1566220,12356900,20680,92490,542970,910090,3218100,7705900,1432900
1989,248239000,14251400,1646040,12605400,21500,94500,578330,951710,3168200,7872400,1564800
1990,248709873,14475600,1820130,12655500,23440,102560,639270,1054860,3073900,7945700,1635900
1991,252177000,14872900,1911770,12961100,24700,106590,687730,1092740,3157200,8142200,1661700
1992,255082000,14438200,1932270,12505900,23760,109060,672480,1126970,2979900,7915200,1610800
1993,257908000,14144800,1926020,12218800,24530,106010,659870,1135610,2834800,7820900,1563100
1994,260341000,13989500,1857670,12131900,23330,102220,618950,1113180,2712800,7879800,1539300
1995,262755000,13862700,1798790,12063900,21610,97470,580510,1099210,2593800,7997700,1472400
1996,265228572,13493863,1688540,11805300,19650,96250,535590,1037050,2506400,7904700,1394200
1997,267637000,13194571,1634770,11558175,18208,96153,498534,1023201,2460526,7743760,1354189
1998,270296000,12475634,1531044,10944590,16914,93103,446625,974402,2329950,7373886,1240754
1999,272690813,11634378,1426044,10208334,15522,89411,409371,911740,2100739,6955520,1152075
2000,281421906,11608072,1425486,10182586,15586,90178,408016,911706,2050992,6971590,1160002
2001,285317559,11876669,1439480,10437480,16037,90863,423557,909023,2116531,7092267,1228391
2002,287973924,11878954,1423677,10455277,16229,95235,420806,891407,2151252,7057370,1246646
2003,290690788,11826538,1383676,10442862,16528,93883,414235,859030,2154834,7026802,1261226
2004,293656842,11679474,1360088,10319386,16148,95089,401470,847381,2144446,6937089,1237851
2005,296507061,11565499,1390745,10174754,16740,94347,417438,862220,2155448,6783447,1235859
2006,299398484,11401511,1418043,9983568,17030,92757,447403,860853,2183746,6607013,1192809
2007,301621157,11251828,1408337,9843481,16929,90427,445125,855856,2176140,6568572,1095769
2008,304374846,11160543,1392628,9767915,16442,90479,443574,842134,2228474,6588046,958629
2009,307006550,10762956,1325896,9337060,15399,89241,408742,812514,2203313,6338095,795652
2010,309330219,10363873,1251248,9112625,14772,85593,369089,781844,2168457,6204601,739565
2011,311587816,10258774,1206031,9052743,14661,84175,354772,752423,2185140,6151095,716508
2012,313873685,10219059,1217067,9001992,14866,85141,355051,762009,2109932,6168874,723186
2013,316497531,9850445,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294
2014,318907401,9395195,1186185,8209010,14164,84864,322905,731089,1713153,5809054,686803
2015,320896618,9258298,1234183,8024115,15883,91261,328109,764057,1587564,5723488,713063
2016,323127513,9202093,1283058,7919035,17250,95730,332198,803007,1515096,5638455,765484

## Problem 2
Create a new column 'Rate' which has the crime rate for each year. Change each column referring to a specific crime to a percentage in relation to the total amount of crime that year. Use this updated table to answer the following questions:

What is the average crime rate? Is the crime rate generally above or below the median?

On average, what is the least common crime?

Identify two crimes which have close averages. Do these two crimes have any kind of correlation on a year to year basis? If so, what is this correlation?

In [20]:
df = pd.read_csv("crime_data.csv", index_col=0)
df["Rate"] = df["Total"] / df["Population"]
df.iloc[:, 2:-1] = df.iloc[:, 2:-1].div(df["Total"], axis=0)
df

,Population,Total,Violent,Property,Murder,Forcible Rape,Robbery,Aggravated Assault,Burglary,Larceny,Vehicle Theft,Rate
Year,,,,,,,,,,,,
1960,179323175,3384200,0.085237,0.914751,0.002692,0.005079,0.031866,0.045600,0.269517,0.548254,0.096980,0.018872
1961,182992000,3488000,0.082967,0.917030,0.002506,0.004937,0.030582,0.044943,0.272248,0.548452,0.096330,0.019061
1962,185771000,3752200,0.080356,0.919647,0.002273,0.004677,0.029545,0.043860,0.264991,0.556900,0.097756,0.020198
1963,188483000,4109500,0.077131,0.922862,0.002102,0.004295,0.028342,0.042392,0.264363,0.559143,0.099355,0.021803
1964,191141000,4564600,0.079792,0.920212,0.002051,0.004693,0.028565,0.044484,0.265785,0.550848,0.103580,0.023881
1965,193526000,4739400,0.081738,0.918260,0.002102,0.004939,0.029263,0.045434,0.270604,0.542811,0.104844,0.024490
1966,195576000,5223500,0.082355,0.917641,0.002114,0.004943,0.030246,0.045052,0.269953,0.540251,0.107438,0.026708
1967,197457000,5903400,0.084685,0.915320,0.002073,0.004679,0.034372,0.043561,0.276468,0.527086,0.111766,0.029897
1968,199399000,6720200,0.088541,0.911461,0.002054,0.004713,0.039112,0.042662,0.276614,0.518244,0.116604,0.033702
1969,201385000,7410900,0.089310,0.910686,0.001992,0.005016,0.040326,0.041977,0.267430,0.524714,0.118542,0.036800
1970,203235298,8098000,0.091235,0.908768,0.001976,0.004691,0.043203,0.041365,0.272289,0.521833,0.114646,0.039845
1971,206212000,8588200,0.095072,0.904928,0.002070,0.004921,0.045143,0.042938,0.279372,0.515149,0.110407,0.041647
1972,208230000,8248800,0.101215,0.898785,0.002263,0.005680,0.045618,0.047654,0.287981,0.503249,0.107555,0.039614
1973,209851000,8718100,0.100470,0.899531,0.002253,0.005896,0.044072,0.048250,0.294273,0.498721,0.106537,0.041544
1974,211392000,10253400,0.095063,0.904939,0.002020,0.005403,0.043147,0.044494,0.296409,0.513244,0.095295,0.048504
1975,213124000,11292400,0.092072,0.907929,0.001816,0.004967,0.041665,0.043624,0.289159,0.529356,0.089405,0.052985
1976,214659000,11349700,0.088479,0.911522,0.001655,0.005029,0.037694,0.044101,0.273902,0.552508,0.085112,0.052873
1977,216332000,10984500,0.093730,0.906277,0.001741,0.005781,0.037563,0.048646,0.279621,0.537639,0.089007,0.050776
1978,218059000,11209000,0.096846,0.903149,0.001745,0.006032,0.038088,0.050982,0.279088,0.534481,0.089580,0.051404
1979,220099000,12249500,0.098619,0.901384,0.001752,0.006236,0.039242,0.051388,0.271660,0.538879,0.090845,0.055655
1980,225349264,13408300,0.100275,0.899719,0.001718,0.006189,0.042201,0.050167,0.283049,0.532275,0.084403,0.059500
1981,229146000,13423800,0.101448,0.898546,0.001678,0.006146,0.044169,0.049457,0.281567,0.535944,0.081035,0.058582
1982,231534000,12974400,0.101923,0.898076,0.001619,0.006071,0.042632,0.051600,0.265685,0.550507,0.081884,0.056037
1983,233981000,12108600,0.103901,0.896099,0.001595,0.006518,0.041836,0.053953,0.258486,0.554383,0.083238,0.051750
1984,236158000,11881800,0.107162,0.892836,0.001573,0.007089,0.040820,0.057681,0.251174,0.554790,0.086872,0.050313
1985,238740000,12431400,0.106891,0.893109,0.001527,0.007133,0.040049,0.058179,0.247221,0.557170,0.088719,0.052071
1986,240132887,13211869,0.112714,0.887286,0.001560,0.006922,0.041082,0.063149,0.245341,0.549290,0.092654,0.055019
1987,242282918,13508700,0.109855,0.890145,0.001488,0.006745,0.038324,0.063299,0.239563,0.555190,0.095396,0.055756
1988,245807000,13923100,0.112491,0.887511,0.001485,0.006643,0.038998,0.065365,0.231134,0.553462,0.102915,0.056642
1989,248239000,14251400,0.115500,0.884503,0.001509,0.006631,0.040581,0.066780,0.222308,0.552395,0.109800,0.057410
1990,248709873,14475600,0.125738,0.874264,0.001619,0.007085,0.044162,0.072872,0.212350,0.548903,0.113011,0.058203
1991,252177000,14872900,0.128540,0.871457,0.001661,0.007167,0.046240,0.073472,0.212279,0.547452,0.111727,0.058978
1992,255082000,14438200,0.133830,0.866168,0.001646,0.007554,0.046576,0.078055,0.206390,0.548212,0.111565,0.056602
1993,257908000,14144800,0.136165,0.863837,0.001734,0.007495,0.046651,0.080285,0.200413,0.552917,0.110507,0.054844
1994,260341000,13989500,0.132790,0.867215,0.001668,0.007307,0.044244,0.079573,0.193917,0.563265,0.110033,0.053735
1995,262755000,13862700,0.129758,0.870242,0.001559,0.007031,0.041876,0.079293,0.187106,0.576922,0.106213,0.052759
1996,265228572,13493863,0.125134,0.874864,0.001456,0.007133,0.039691,0.076853,0.185744,0.585800,0.103321,0.050876
1997,267637000,13194571,0.123897,0.875980,0.001380,0.007287,0.037783,0.077547,0.186480,0.586890,0.102632,0.049300
1998,270296000,12475634,0.122723,0.877277,0.001356,0.007463,0.035800,0.078104,0.186760,0.591063,0.099454,0.046155
1999,272690813,11634378,0.122572,0.877428,0.001334,0.007685,0.035186,0.078366,0.180563,0.597842,0.099023,0.042665
2000,281421906,11608072,0.122801,0.877199,0.001343,0.007769,0.035149,0.078541,0.176687,0.600581,0.099931,0.041248
2001,285317559,11876669,0.121202,0.878822,0.001350,0.007651,0.035663,0.076539,0.178209,0.597160,0.103429,0.041626
2002,287973924,11878954,0.119849,0.880151,0.001366,0.008017,0.035424,0.075041,0.181098,0.594107,0.104946,0.041250
2003,290690788,11826538,0.116998,0.883002,0.001398,0.007938,0.035026,0.072636,0.182203,0.594155,0.106644,0.040684
2004,293656842,11679474,0.116451,0.883549,0.001383,0.008142,0.034374,0.072553,0.183608,0.593956,0.105985,0.039773
2005,296507061,11565499,0.120249,0.879751,0.001447,0.008158,0.036093,0.074551,0.186369,0.586524,0.106857,0.039006
2006,299398484,11401511,0.124373,0.875636,0.001494,0.008136,0.039241,0.075503,0.191531,0.579486,0.104619,0.038081
2007,301621157,11251828,0.125165,0.874834,0.001505,0.008037,0.039560,0.076064,0.193403,0.583778,0.097386,0.037305
2008,304374846,11160543,0.124781,0.875219,0.001473,0.008107,0.039745,0.075456,0.199674,0.590298,0.085894,0.036667
2009,307006550,10762956,0.123191,0.867518,0.001431,0.008291,0.037977,0.075492,0.204713,0.588881,0.073925,0.035058
2010,309330219,10363873,0.120732,0.879268,0.001425,0.008259,0.035613,0.075439,0.209232,0.598676,0.071360,0.033504
2011,311587816,10258774,0.117561,0.882439,0.001429,0.008205,0.034582,0.073344,0.213002,0.599594,0.069843,0.032924
2012,313873685,10219059,0.119098,0.880902,0.001455,0.008332,0.034744,0.074567,0.206470,0.603664,0.070768,0.032558
2013,316497531,9850445,0.121790,0.878210,0.001454,0.008336,0.035033,0.073761,0.196117,0.611001,0.071093,0.031123
2014,318907401,9395195,0.126254,0.873746,0.001508,0.009033,0.034369,0.077815,0.182344,0.618301,0.073102,0.029461
2015,320896618,9258298,0.133306,0.866694,0.001716,0.009857,0.035439,0.082527,0.171475,0.618201,0.077019,0.028851
2016,323127513,9202093,0.139431,0.860569,0.001875,0.010403,0.036100,0.087264,0.164647,0.612736,0.083186,0.028478

In [21]:
df.describe()

,Population,Total,Violent,Property,Murder,Forcible Rape,Robbery,Aggravated Assault,Burglary,Larceny,Vehicle Theft,Rate
count,5.700000e+01,5.700000e+01,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000,57.000000
mean,2.488181e+08,1.055356e+07,0.109324,0.890511,0.001710,0.006747,0.038258,0.062361,0.231930,0.561886,0.096701,0.042369
std,4.326907e+07,3.129618e+06,0.017375,0.017551,0.000319,0.001446,0.004766,0.014932,0.041628,0.030905,0.013211,0.011865
min,1.793232e+08,3.384200e+06,0.077131,0.860569,0.001334,0.004295,0.028342,0.041365,0.164647,0.498721,0.069843,0.018872
25%,2.113920e+08,9.202093e+06,0.095063,0.875980,0.001456,0.005403,0.035149,0.045600,0.191531,0.540251,0.086872,0.033504
50%,2.458070e+08,1.134970e+07,0.112714,0.887286,0.001619,0.007031,0.038324,0.065365,0.231134,0.554383,0.099355,0.041544
75%,2.879739e+08,1.297440e+07,0.123191,0.904939,0.001976,0.007938,0.041836,0.075503,0.271660,0.590298,0.106644,0.052873
max,3.231275e+08,1.487290e+07,0.139431,0.922862,0.002692,0.010403,0.046651,0.087264,0.296409,0.618301,0.118542,0.059500

What is the average crime rate? Is the crime rate generally above or below the median?

0.042369, Above the median

On average, what is the least common crime?

Murder

Identify two crimes which have close averages. Do these two crimes have any kind of correlation on a year to year basis? If so, what is this correlation?

Robbery and Assault. It seems that Robbery stayed closed to the average while Assault consistently went up higher as years went by

## Problem 3
Answer the following questions using the functions described above. Support your answers with data from the file.

In what year did most crimes hit an all-time high in the U.S.?

Which decade had the greatest amount of total crime?

Which crime was commited most during this decade?

In [63]:
df = pd.read_csv("crime_data.csv", index_col=0)
print(df.max())
for i in range(2, 11):
    ind = np.where(df.iloc[:,i] == df.max()[i])[0][0]
    print(df.iloc[ind])

Population            323127513
Total                  14872900
Violent                 1932270
Property               12961100
Murder                    24700
Forcible Rape            109060
Robbery                  687730
Aggravated Assault      1135610
Burglary                3795200
Larceny                 8142200
Vehicle Theft           1661700
dtype: int64
Population            255082000
Total                  14438200
Violent                 1932270
Property               12505900
Murder                    23760
Forcible Rape            109060
Robbery                  672480
Aggravated Assault      1126970
Burglary                2979900
Larceny                 7915200
Vehicle Theft           1610800
Name: 1992, dtype: int64
Population            252177000
Total                  14872900
Violent                 1911770
Property               12961100
Murder                    24700
Forcible Rape            106590
Robbery                  687730
Aggravated Assault      1092740
Burglary                3157200
Larceny                 8142200
Vehicle Theft           1661700
Name: 1991, dtype: int64
Population            252177000
Total                  14872900
Violent                 1911770
Property               12961100
Murder                    24700
Forcible Rape            106590
Robbery                  687730
Aggravated Assault      1092740
Burglary                3157200
Larceny                 8142200
Vehicle Theft           1661700
Name: 1991, dtype: int64
Population            255082000
Total                  14438200
Violent                 1932270
Property               12505900
Murder                    23760
Forcible Rape            109060
Robbery                  672480
Aggravated Assault      1126970
Burglary                2979900
Larceny                 7915200
Vehicle Theft           1610800
Name: 1992, dtype: int64
Population            252177000
Total                  14872900
Violent                 1911770
Property               12961100
Murder                    24700
Forcible Rape            106590
Robbery                  687730
Aggravated Assault      1092740
Burglary                3157200
Larceny                 8142200
Vehicle Theft           1661700
Name: 1991, dtype: int64
Population            257908000
Total                  14144800
Violent                 1926020
Property               12218800
Murder                    24530
Forcible Rape            106010
Robbery                  659870
Aggravated Assault      1135610
Burglary                2834800
Larceny                 7820900
Vehicle Theft           1563100
Name: 1993, dtype: int64
Population            225349264
Total                  13408300
Violent                 1344520
Property               12063700
Murder                    23040
Forcible Rape             82990
Robbery                  565840
Aggravated Assault       672650
Burglary                3795200
Larceny                 7136900
Vehicle Theft           1131700
Name: 1980, dtype: int64
Population            252177000
Total                  14872900
Violent                 1911770
Property               12961100
Murder                    24700
Forcible Rape            106590
Robbery                  687730
Aggravated Assault      1092740
Burglary                3157200
Larceny                 8142200
Vehicle Theft           1661700
Name: 1991, dtype: int64
Population            252177000
Total                  14872900
Violent                 1911770
Property               12961100
Murder                    24700
Forcible Rape            106590
Robbery                  687730
Aggravated Assault      1092740
Burglary                3157200
Larceny                 8142200
Vehicle Theft           1661700
Name: 1991, dtype: int64

In [81]:
print(df.iloc[0:10].cumsum().iloc[-1,1])
for i in range(6):
    print("{}'s:".format(1960+10*i), df.iloc[10*i:10*(i+1)].cumsum().iloc[-1,1])

49295900
1960's: 49295900
1970's: 100991600
1980's: 131123369
1990's: 136582146
2000's: 115012044
2010's: 68547737

In [82]:
df.iloc[30:40].cumsum().iloc[-1]

Population            2612825258
Total                  136582146
Violent                 17527048
Property               119053499
Murder                    211664
Forcible Rape             998827
Robbery                  5748930
Aggravated Assault      10568963
Burglary                26750015
Larceny                 77679366
Vehicle Theft           14624418
Name: 1999, dtype: int64

In what year did most crimes hit an all-time high in the U.S.?
1991

Which decade had the greatest amount of total crime?
1990s

Which crime was commited most during this decade?
Larceny

## Problem 4
Using panda commands, find the crime rates of the years where Property crimes were less than 90% of the total crime and burglary crimes were more than 20% of the total crime or property crimes were less than 90% of the total crime while violent crimes were more than 20% of the total crime.

In [147]:
# There was no instance of violent crimes being more thant 20%
df = pd.read_csv("crime_data.csv", index_col=0)
df["Rate"] = df["Total"] / df["Population"]
df.iloc[:, 2:-1] = df.iloc[:, 2:-1].div(df["Total"], axis=0)
m = df[df["Property"] < 0.9]
m = m[m["Burglary"] > 0.2]
m

,Population,Total,Violent,Property,Murder,Forcible Rape,Robbery,Aggravated Assault,Burglary,Larceny,Vehicle Theft,Rate
Year,,,,,,,,,,,,
1972,208230000,8248800,0.101215,0.898785,0.002263,0.005680,0.045618,0.047654,0.287981,0.503249,0.107555,0.039614
1973,209851000,8718100,0.100470,0.899531,0.002253,0.005896,0.044072,0.048250,0.294273,0.498721,0.106537,0.041544
1980,225349264,13408300,0.100275,0.899719,0.001718,0.006189,0.042201,0.050167,0.283049,0.532275,0.084403,0.059500
1981,229146000,13423800,0.101448,0.898546,0.001678,0.006146,0.044169,0.049457,0.281567,0.535944,0.081035,0.058582
1982,231534000,12974400,0.101923,0.898076,0.001619,0.006071,0.042632,0.051600,0.265685,0.550507,0.081884,0.056037
1983,233981000,12108600,0.103901,0.896099,0.001595,0.006518,0.041836,0.053953,0.258486,0.554383,0.083238,0.051750
1984,236158000,11881800,0.107162,0.892836,0.001573,0.007089,0.040820,0.057681,0.251174,0.554790,0.086872,0.050313
1985,238740000,12431400,0.106891,0.893109,0.001527,0.007133,0.040049,0.058179,0.247221,0.557170,0.088719,0.052071
1986,240132887,13211869,0.112714,0.887286,0.001560,0.006922,0.041082,0.063149,0.245341,0.549290,0.092654,0.055019
1987,242282918,13508700,0.109855,0.890145,0.001488,0.006745,0.038324,0.063299,0.239563,0.555190,0.095396,0.055756
1988,245807000,13923100,0.112491,0.887511,0.001485,0.006643,0.038998,0.065365,0.231134,0.553462,0.102915,0.056642
1989,248239000,14251400,0.115500,0.884503,0.001509,0.006631,0.040581,0.066780,0.222308,0.552395,0.109800,0.057410
1990,248709873,14475600,0.125738,0.874264,0.001619,0.007085,0.044162,0.072872,0.212350,0.548903,0.113011,0.058203
1991,252177000,14872900,0.128540,0.871457,0.001661,0.007167,0.046240,0.073472,0.212279,0.547452,0.111727,0.058978
1992,255082000,14438200,0.133830,0.866168,0.001646,0.007554,0.046576,0.078055,0.206390,0.548212,0.111565,0.056602
1993,257908000,14144800,0.136165,0.863837,0.001734,0.007495,0.046651,0.080285,0.200413,0.552917,0.110507,0.054844
2009,307006550,10762956,0.123191,0.867518,0.001431,0.008291,0.037977,0.075492,0.204713,0.588881,0.073925,0.035058
2010,309330219,10363873,0.120732,0.879268,0.001425,0.008259,0.035613,0.075439,0.209232,0.598676,0.071360,0.033504
2011,311587816,10258774,0.117561,0.882439,0.001429,0.008205,0.034582,0.073344,0.213002,0.599594,0.069843,0.032924
2012,313873685,10219059,0.119098,0.880902,0.001455,0.008332,0.034744,0.074567,0.206470,0.603664,0.070768,0.032558

## Problem 5
Read in the files `final_accidents2.pickle` and `final_drivers.pickle` using the function `read_pickle()`.  
The accidents file contains data on various accidents that occured in the U.S. and their causes.
The drivers data has data on various tickets given to drivers, how many tickets given, and what the ticket is for.

Create a `DataFrame` containing the Case Number, Age, whether the accident was caused by a drunk driver, whether the driver had DUIs, and if the accident was fatal, using an inner join operation.
Create a second `DataFrame` containing Case Number, Age, and fatalities using an inner join operation. In this `DataFrame`, also include the speed column from each dataframe.

In [98]:
accidents = pd.read_pickle("final_accidents2.pickle")
drivers = pd.read_pickle("final_drivers.pickle")
df1 = pd.merge(accidents, drivers, on="ST_CASE")[["ST_CASE", "AGE", "DRUNK_DR", "DRINKING", "FATALS"]]
df1

         ST_CASE  AGE  DRUNK_DR  DRINKING  FATALS
0          10001   51         1         9       1
1          10001   55         1         9       1
2          10001   22         1         0       1
3          10001   28         1         0       1
4          10001   24         1         1       1
5          10001   51         1         9       1
6          10001   55         1         9       1
7          10001   22         1         0       1
8          10001   28         1         0       1
9          10001   24         1         1       1
10         10001   51         1         9       1
11         10001   55         1         9       1
12         10001   22         1         0       1
13         10001   28         1         0       1
14         10001   24         1         1       1
15         10001   51         0         9       2
16         10001   55         0         9       2
17         10001   22         0         0       2
18         10001   28         0         0       2
19         10001   24         0         1       2
20         10001   51         1         9       1
21         10001   55         1         9       1
22         10001   22         1         0       1
23         10001   28         1         0       1
24         10001   24         1         1       1
25         10002   44         0         0       1
26         10002   24         0         9       1
27         10002   10         0         0       1
28         10002   40         0         0       1
29         10002   67         0         0       1
...          ...  ...       ...       ...     ...
1053208   490228   26         0         0       1
1053209   490229   34         0         0       2
1053210   490230   32         1         1       1
1053211   490231   31         0         0       2
1053212   490231   34         0         0       2
1053213   530435   84         0         8       1
1053214   530436   18         0         0       1
1053215   530437   32         0         0       1
1053216   530437   18         0         0       1
1053217   530438   35         1         1       1
1053218   530439   46         0         9       1
1053219   530440   32         0         0       1
1053220   530442   26         0         9       1
1053221   530443   68         0         9       1
1053222   530444   58         1         1       1
1053223   530444   50         1         9       1
1053224   530444   30         1         0       1
1053225   530445   25         1         9       1
1053226   530445   55         1         0       1
1053227   530447   67         0         8       1
1053228   530448   64         0         8       1
1053229   530449   20         0         9       1
1053230   530449   47         0         9       1
1053231   530450   33         0         0       1
1053232   530451   78         0         0       1
1053233   530451   45         0         0       1
1053234   530451   46         0         0       1
1053235   530452   38         0         0       1
1053236   530452   61         0         0       1
1053237   530453   31         0         8       1

[1053238 rows x 5 columns]

In [101]:
df2 = pd.merge(accidents, drivers, on="ST_CASE")[["ST_CASE", "AGE", "FATALS", "SP", "SPEEDREL"]]
df2

         ST_CASE  AGE  FATALS  SP  SPEEDREL
0          10001   51       1   0         0
1          10001   55       1   0         0
2          10001   22       1   0         0
3          10001   28       1   0         0
4          10001   24       1   0         3
5          10001   51       1   0         0
6          10001   55       1   0         0
7          10001   22       1   0         0
8          10001   28       1   0         0
9          10001   24       1   0         3
10         10001   51       1   0         0
11         10001   55       1   0         0
12         10001   22       1   0         0
13         10001   28       1   0         0
14         10001   24       1   0         3
15         10001   51       2   0         0
16         10001   55       2   0         0
17         10001   22       2   0         0
18         10001   28       2   0         0
19         10001   24       2   0         3
20         10001   51       1   1         0
21         10001   55       1   1         0
22         10001   22       1   1         0
23         10001   28       1   1         0
24         10001   24       1   1         3
25         10002   44       1   0         0
26         10002   24       1   0         0
27         10002   10       1   0         0
28         10002   40       1   0         0
29         10002   67       1   0         0
...          ...  ...     ...  ..       ...
1053208   490228   26       1   1         3
1053209   490229   34       2   0         0
1053210   490230   32       1   0         9
1053211   490231   31       2   0         0
1053212   490231   34       2   0         0
1053213   530435   84       1   0         0
1053214   530436   18       1   1         4
1053215   530437   32       1   0         0
1053216   530437   18       1   0         0
1053217   530438   35       1   1         4
1053218   530439   46       1   1         4
1053219   530440   32       1   0         0
1053220   530442   26       1   0         0
1053221   530443   68       1   0         0
1053222   530444   58       1   0         0
1053223   530444   50       1   0         0
1053224   530444   30       1   0         0
1053225   530445   25       1   1         4
1053226   530445   55       1   1         0
1053227   530447   67       1   0         9
1053228   530448   64       1   0         9
1053229   530449   20       1   1         4
1053230   530449   47       1   1         0
1053231   530450   33       1   0         0
1053232   530451   78       1   0         0
1053233   530451   45       1   0         0
1053234   530451   46       1   0         0
1053235   530452   38       1   0         0
1053236   530452   61       1   0         0
1053237   530453   31       1   0         0

[1053238 rows x 5 columns]

## Problem 6

1. What is the most common kind of weather involved with accidents?

2. How often did speeding get reported in accidents?

3. Of accidents where the type of speeding is known, what is the most common type of speeding in accidents?

4. On average, how many drunk drivers are involved in an accident?

5. What month has the most fatalities each year?

In [118]:
accidents.mode(axis=0).iloc[0]

ST_CASE     10001.000000
STATE          48.000000
LATITUDE       28.542639
LONGITUD     -118.309022
HOUR           18.000000
DAY             1.000000
MONTH           8.000000
YEAR         2012.000000
DRUNK_DR        0.000000
WEATHER         1.000000
SP              0.000000
FATALS          1.000000
Name: 0, dtype: float64

In [115]:
spr = df2[df2["SPEEDREL"]>1]
spr = spr[spr["SPEEDREL"]<8]
len(spr) / len(df2)

0.07737757278032126

In [121]:
df2[df2["SPEEDREL"]==9].mode()

   ST_CASE    AGE  FATALS   SP  SPEEDREL
0   220052  999.0     1.0  0.0       9.0
1   440015    NaN     NaN  NaN       NaN
2   440028    NaN     NaN  NaN       NaN

In [124]:
accidents.describe()

,ST_CASE,STATE,LATITUDE,LONGITUD,HOUR,DAY,MONTH,YEAR,DRUNK_DR,WEATHER,SP,FATALS
count,148206.000000,148206.000000,148206.000000,148206.000000,148206.000000,148206.000000,148206.000000,148206.000000,148206.000000,148206.000000,148206.000000,148206.000000
mean,280064.232946,27.943963,36.704845,-91.815633,12.638557,15.663320,6.753856,2012.000432,0.313483,2.815534,0.295757,1.089301
std,162307.103941,16.234001,5.165450,14.717386,6.929258,8.847314,3.347173,1.411410,0.484263,5.699032,0.456384,0.360859
min,10001.000000,0.000000,18.960467,-165.407103,0.000000,1.000000,1.000000,2010.000000,0.000000,1.000000,0.000000,1.000000
25%,122094.000000,12.000000,33.237144,-97.673128,7.000000,8.000000,4.000000,2011.000000,0.000000,1.000000,0.000000,1.000000
50%,280228.000000,28.000000,36.578921,-87.688676,14.000000,16.000000,7.000000,2012.000000,0.000000,1.000000,0.000000,1.000000
75%,420772.000000,42.000000,40.653129,-81.306327,18.000000,23.000000,10.000000,2013.000000,1.000000,2.000000,1.000000,1.000000
max,560137.000000,56.000000,68.433764,-66.993169,23.000000,31.000000,12.000000,2014.000000,4.000000,98.000000,1.000000,15.000000

In [144]:
fatals_per_month = []
for i in range(1, 13):
    x = accidents[accidents["MONTH"]==i].cumsum().iloc[-1,-1]
    fatals_per_month.append((i, x))
print(sorted(fatals_per_month, key=lambda x: x[1]))

[(2, 10363.0), (1, 11591.0), (3, 12323.0), (4, 12745.0), (12, 13291.0), (11, 13910.0), (5, 13961.0), (6, 14177.0), (9, 14304.0), (10, 14820.0), (7, 14900.0), (8, 15056.0)]

1. What is the most common kind of weather involved with accidents?

clear

2. How often did speeding get reported in accidents?

7.74%

3. Of accidents where the type of speeding is known, what is the most common type of speeding in accidents?

Not Speeding

4. On average, how many drunk drivers are involved in an accident?

0.313

5. What month has the most fatalities each year?

August